
- name: Configure emacs
  block:
    - name: Clone spacemacs base
      git:
        repo: "{{spacemacs_clone_url}}"
        dest: "~/.emacs.d"
    - name: Install dotspacemacs
      copy:
        src: dotspacemacs
        dest: "~/.spacemacs"
      tags:
        - sync-config
    - name: Install emacs daemon service file
      block:
        - name: "Make .config"
          file:
            path: "~/.config/systemd/user"
            state: directory
        - name: "Generate emacs.service"
          template:
            src: emacs.service
            dest: "~/.config/systemd/user/emacs.service"
          tags:
            - sync-config
    - name: Enable systemd emacs user service
      systemd:
        name: emacs.service
        scope: user
        enabled: yes
        state: started
  tags:
    - editor
    - configuration

# - name: Sync spacemacs packages
#   command: emacsclient -s {{ ansible_facts["user_id"] }} --eval '(dotspacemacs/sync-configuration-layers)'
