#
# Install user-local font patches.
#

- name: Install user font patches
  block:
    - name: Make local font directory
      file:
        path: "~/.local/share/fonts"
        state: directory
    - name: Sync custom fonts
      copy:
        src: anonymous-pro-qwattash/AnonymousProQwattash.ttf
        dest: "~/.local/share/fonts/AnonymousProQwattash.ttf"
    - name: Rebuild font cache
      command: fc-cache -f -v
