#
# Configure oh-my-zsh
#

- name: Clone oh-my-zsh base
  git:
    repo: "{{ ohmyzsh_clone_url }}"
    dest: "~/.oh-my-zsh"

- name: Sync oh-my-zsh custom configs
  copy:
    src: "zsh-custom/"
    dest: "~/.oh-my-zsh/custom"
    force: yes

- name: Install dotzshrc
  template:
    src: dotzshrc
    dest: "~/.zshrc"
