#
# Configure oh-my-zsh
#

- name: Clone oh-my-zsh base
  git:
    repo: "{{ ohmyzsh_clone_url }}"
    dest: "~/.oh-my-zsh"

# XXX-AM: this causes continue synchronization, find a way to avoid it.
- name: Empty oh-my-zsh custom directory
  file:
    state: absent
    path: "~/.oh-my-zsh/custom"

- name: Clone oh-my-zsh custom configs
  git:
    repo: "{{ ohmyzsh_custom_url }}"
    dest: "~/.oh-my-zsh/custom"

- name: Reset oh-my-zsh files
  command: git reset --hard HEAD
  args:
    chdir: "~/.oh-my-zsh"

- name: Install dotzshrc
  template:
    src: dotzshrc
    dest: "~/.zshrc"
