
- name: Make .Xresources file
  template:
    src: dotxresources
    dest: "{{ user_home }}/.Xresources"

- name: Make ansible_managed config directory
  file:
    path: "{{ user_home }}/.config/ansible_managed"
    state: directory

- import_tasks: urxvt.yml
- import_tasks: kitty.yml
