#
# Setup awesome WM configuration.
#

- name: Install AwesomeWM top level configuration
  block:
    - name: Make .config/awesome
      file:
        path: "~/.config/awesome"
        state: directory
    - name: Sync rc.lua
      copy:
        src: awesome_main_full.lua
        dest: "~/.config/awesome/rc.lua"

# - name: Install AwesomeWM configuration components
#   block:
#     - name: Install layout configi
#     - name: Install wallpaper config
#     - name: Install menubar config
#     - name: Install key bindings config
#     - name: Install clients config
#     - name: Install widget config

# - name: Clone awesome theme repository
#   git:
#     repo: "{{ base16_awesome_clone_url }}"
#     dest: "~/{{ user_local_confdir }}/base16_awesome"
