#
# Setup awesome WM configuration.
#

# - name: Install AwesomeWM top level configuration
#   block:
#     - name: Make .config/awesome
#       file:
#         path: "~/.config/awesome"
#         state: directory
#     - name: Sync rc.lua
#       copy:
#         src: awesome_main_full.lua
#         dest: "~/.config/awesome/rc.lua"

- name: Install AwesomeWM configuration components
  block:
    - name: Make .config/awesome
      file:
        path: "~/.config/awesome"
        state: directory
    - name: Make slave config directory
      file:
        path: "~/{{ user_local_confdir }}/awesome"
        state: directory
    - name: Sync rc.lua
      template:
        src: awesome_main.lua
        dest: "~/.config/awesome/rc.lua"
    - name: Sync configuration modules
      copy:
        src: awesome/qwattash_conf
        dest: "~/{{ user_local_confdir }}/awesome"
    - name: Sync theme configuration directory
      file:
        path: "~/{{ user_local_confdir }}/awesome/theme"
        state: directory
    - name: Sync theme configuration
      template:
        src: awesome_theme.lua
        dest: "~/{{ user_local_confdir }}/awesome/theme/theme.lua"
    - name: Sync theme files
      copy:
        src: awesome/themes/icons
        dest: "~/{{ user_local_confdir }}/awesome/theme"
